### ISSUE TITLE
Propose the Study

### ISSUE THREAD

**Issue by mickey-barron** [ec-belonging-in-biology/sci-id-development#22]
Propose the study to the ethics committee via request for exemption form with associated instruments and protocols.

These items must be completed prior to submission:
- [x] Complete Quantification of Sci ID (QOS) survey instrument
- [ ]  Complete Qualitative Identity Index (QII) survey instrument #21
- [ ] Complete Instructor Guidelines Adherence Rating (IGAR) Instrument  #18
- [ ] Compose instructor participant informed consent #17
- [ ] Compose student participant informed consent #20
- [ ] Establish data management protocols #16
